### ISSUE TITLE
Error when install CellO

### ISSUE THREAD

**Issue by Chrisdoan9** [deweylab/CellO#28]
Hello all,
I run:

`pip install pygraphviz leidenalg scanpy cello-classify`

And this was what I got:

     pygraphviz/graphviz_wrap.c:2711:10: fatal error: 'graphviz/cgraph.h' file not found
      #include "graphviz/cgraph.h"
               ^~~~~~~~~~~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pygraphviz

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

[notice] A new release of pip available: 22.2.2 -> 22.3
[notice] To update, run: python3.9 -m pip install --upgrade pip
(cello_env) 

Would you please suggest how to fix this? Thank you so much!

**Comment by mbernste** [comment]
Hi, it looks like this is an issue with your graphviz installation. Do you know how you installed graphviz? I would recommend using conda:
 
`conda install -c anaconda graphviz`

**Comment by Chrisdoan9** [comment]
Thank you!

`conda install -c anaconda graphviz` returned no error, however:

`pip install pygraphviz leidenalg scanpy cello-classify`

 #include "graphviz/cgraph.h"
                                   ^
      compilation terminated.
      error: command '/usr/lib64/ccache/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pygraphviz

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by mbernste** [comment]
Sorry to hear you are still having trouble. You may want to try installing pygraphviz through conda as well: https://anaconda.org/conda-forge/pygraphviz

**Comment by Chrisdoan9** [comment]
Thank you! It worked!

`model_prefix = 'GSM3516673_MSK_LX682_NORMAL′`

  File "<stdin>", line 1
    model_prefix = 'GSM3516673_MSK_LX682_NORMAL′
                                                ^
SyntaxError: EOL while scanning string literal

Would you please tell me how to fix this?

**Comment by Chrisdoan9** [comment]
Hi,

I installed cello on a server, so it is different from a local computer when open Jupiter notebook. When I copied and pasted the URL as the instruction, I could not open Jupiter notebook. Would you please have a suggestion? Or I should install Cello on a local computer? Thank you so much!

(cello_env) [user@fenn03 ~]$ jupyter notebook cello_tutorial.ipynb
[I 14:02:24.637 NotebookApp] Serving notebooks from local directory: /home/user
[I 14:02:24.637 NotebookApp] Jupyter Notebook 6.5.1 is running at:
[I 14:02:24.637 NotebookApp] http://localhost:8888/?token=57c5937d21cc7ab01ceb08b66ba0a6bbfa45c7625175802d
[I 14:02:24.637 NotebookApp]  or http://127.0.0.1:8888/?token=57c5937d21cc7ab01ceb08b66ba0a6bbfa45c7625175802d
[I 14:02:24.637 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 14:02:24.650 NotebookApp] No web browser found: could not locate runnable browser.
[C 14:02:24.650 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/user/.local/share/jupyter/runtime/nbserver-30005-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=57c5937d21cc7ab01ceb08b66ba0a6bbfa45c7625175802d
     or http://127.0.0.1:8888/?token=57c5937d21cc7ab01ceb08b66ba0a6bbfa45c7625175802d

**Comment by mbernste** [comment]
Hi Christ, Here's an article that may help you running a Jupyter notebook on a remote server using port forwarding: https://docs.anaconda.com/anaconda/user-guide/tasks/remote-jupyter-notebook/

**Comment by Chrisdoan9** [comment]
> Thank you! It worked!
> 
> `model_prefix = 'GSM3516673_MSK_LX682_NORMAL′`
> 
> File "", line 1 model_prefix = 'GSM3516673_MSK_LX682_NORMAL′ ^ SyntaxError: EOL while scanning string literal
> 
> Would you please tell me how to fix this? Should I open a new issue or I can post the error here? Thank you.

Thank you for the information! Do you have any suggestions for this issue?

**Comment by cndewey** [comment]
It looks like your end quote character is not a standard Python quote character.  Use ' instead of ′

**Comment by Chrisdoan9** [comment]
Thank you so much! I copied code from the paper and didn't check it.

**Comment by Chrisdoan9** [comment]
Hi,

Would you please have a look at this?

>>> ```
cello.scanpy_cello(

 adata,

 clust_key='leiden',

 rsrc_loc=cello_resource_loc,

 out_prefix=model_prefix,

 log_dir=os.getcwd()

)
```

        Could not find the CellO resources directory called
        'resources' in '/vcu_gpfs2/home/doanc2'. Will download resources to current 
        directory.
        
Running command: curl http://deweylab.biostat.wisc.edu/cell_type_classification/resources_v2.0.0.tar.gz > /home/user/resources_v2.0.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   266  100   266    0     0   3782      0 --:--:-- --:--:-- --:--:--  3855
Running command: tar -C /home/user -zxf resources_v2.0.0.tar.gz

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Running command: rm /vcu_gpfs2/home/doanc2/resources_v2.0.0.tar.gz
Checking if any pre-trained model is compatible with this input dataset...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/miniconda3/envs/cello_env/lib/python3.7/site-packages/cello/scanpy_cello.py", line 129, in cello
    mod = ce._retrieve_pretrained_model(adata, algo, rsrc_loc)
  File "/home/user/miniconda3/envs/cello_env/lib/python3.7/site-packages/cello/cello.py", line 331, in _retrieve_pretrained_model
    with open(model_f, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/resources/trained_models/ir.dill'

**Comment by Chrisdoan9** [comment]
Hi,

Just check-in in case you weren't notified.
